// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGmCOcAZjFPXBxdVEQru36PaynwpvY3U',
    appId: '1:796618306938:web:4fc2c8d0eeede4cff312c3',
    messagingSenderId: '796618306938',
    projectId: 'lab3-3ee4e',
    authDomain: 'lab3-3ee4e.firebaseapp.com',
    storageBucket: 'lab3-3ee4e.firebasestorage.app',
    measurementId: 'G-3SL05VHNBG',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SDbPvHsVRDiOO2Wt9twCVDVgV8D6Fv4',
    appId: '1:796618306938:android:9e4c646db228feeff312c3',
    messagingSenderId: '796618306938',
    projectId: 'lab3-3ee4e',
    storageBucket: 'lab3-3ee4e.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC81WCRxRGbvgn3D5h4Ar8iCERua7DWOEI',
    appId: '1:796618306938:ios:c28768a07117904cf312c3',
    messagingSenderId: '796618306938',
    projectId: 'lab3-3ee4e',
    storageBucket: 'lab3-3ee4e.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC81WCRxRGbvgn3D5h4Ar8iCERua7DWOEI',
    appId: '1:796618306938:ios:c28768a07117904cf312c3',
    messagingSenderId: '796618306938',
    projectId: 'lab3-3ee4e',
    storageBucket: 'lab3-3ee4e.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGmCOcAZjFPXBxdVEQru36PaynwpvY3U',
    appId: '1:796618306938:web:63a307d35a2698e1f312c3',
    messagingSenderId: '796618306938',
    projectId: 'lab3-3ee4e',
    authDomain: 'lab3-3ee4e.firebaseapp.com',
    storageBucket: 'lab3-3ee4e.firebasestorage.app',
    measurementId: 'G-8D7DR3T365',
  );
}
